### ISSUE TITLE
Lazy load mapbox/pass mapbox object in

### ISSUE THREAD

**Issue by fer22f** [soal/vue-mapbox#102]
So, I have a script to add the mapbox API to my app lazily. That means that it only gets added to the document once a specific view is added. 0.1.x versions of vue-mapbox allowed for a delayed `Vue.use` loading which made this work, however in 0.2.x, it directly imports `mapbox-gl` making this impossible.

This is a bit troublesome, but the dependency inversion principle in this case is very important.

**Comment by soal** [comment]
Well, it would be possible to implement passing `mapbox-gl` as a prop to MglMap.
Would it be enough?

**Comment by fer22f** [comment]
I think so yes.

The thing is this line:
https://github.com/soal/vue-mapbox/blob/0cf07c548fad16a5959ad613f66d8cf28203bf1d/src/components/map/GlMap.vue#L9

It has to be "removed", i.e., converted into a dynamic `import()`:

```javascript
created () {
  this.mapboxPromise = this.mapboxGl ? Promise.resolve(this.mapboxGl) : import('mapbox-gl')
}

// ...

$_loadMap () {
  return this.mapboxPromise.then(mapbox => {
    this.mapbox = mapbox
    return new Promise(resolve => {
      // ...
    })
  })
}
```

So that it only happens if the user doesn't pass in anything.

**Comment by Erutan409** [comment]
@soal What would be a good way to avoid pulling in the entire mapbox-gl package during a webpack/babel compile?  This is a lot of boilerplate for something I'm loading from a CDN, already.

With my current configuration, it's extracting out that asset into an obscure zero-based incremented javascript file at the root of my public build folder.  I'm curious if you know a straight-forward way of avoiding that all together.

**Comment by ViachaslauBohdan** [comment]
@soal @fer22f @Erutan409 
Guys, can you explain why mapboxGL param is needed. Because anyhow with pure v-if wrapper the map is loaded lazily

**Comment by ferk6a** [comment]
> @soal @fer22f @Erutan409
> Guys, can you explain why mapboxGL param is needed. Because anyhow with pure v-if wrapper the map is loaded lazily

I no longer use this package and sorry for the late response, but the problem is that vue-mapbox previously made an `import` at the top of the file, and we would like to use the CDN instead of bundling the Mapbox API. The prop made this possible.
