### ISSUE TITLE
problem with webpack and JS Spread syntax

### ISSUE THREAD

**Issue by tpoussard** [soal/vue-mapbox#104]
Hye, thanks for carrying on the good job of korigan with mapbox. I'm currently trying to replace gmap with mapbox, I did it succesfully with leaflet (vue2leaflet) and the wrapper of [phegman](https://github.com/phegman/vue-mapbox-gl), but I encouter a problem when trying your wrapper and I don't see where it can come from. Apparently, webpack cannot build and it looks like there is a problem with the spread syntax :

 ERROR  Failed to compile with 11 errors                                14:45:33

 error  in ./node_modules/vue-mapbox/src/components/layer/GeojsonLayer.js

Module parse failed: Unexpected token (110:10)
You may need an appropriate loader to handle this file type.
|         const source = {
|           type: "geojson",
|           ...this.source
|         };
|         try {

 @ ./node_modules/vue-mapbox/src/main.js 11:0-59
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?typ
e=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

 error  in ./node_modules/vue-mapbox/src/components/map/mixins/withAsyncActions.js

Module parse failed: Unexpected token (11:8)
You may need an appropriate loader to handle this file type.
|     $_registerAsyncActions(map) {
|       this.actions = {
|         ...promisify(map),
|         stop() {
|           this.map.stop();

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-mapbox/src/components/map/GlMap.vue 16:0-57
 @ ./node_modules/vue-mapbox/src/components/map/GlMap.vue
 @ ./node_modules/vue-mapbox/src/main.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

 error  in ./node_modules/vue-mapbox/src/lib/withEvents.js

Module parse failed: Unexpected token (13:8)
You may need an appropriate loader to handle this file type.
|         map: this.map,
|         component: this,
|         ...data
|       });
|     },

 @ ./node_modules/vue-mapbox/src/main.js 18:0-47
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

 error  in ./node_modules/vue-mapbox/src/components/layer/RasterLayer.js

Module parse failed: Unexpected token (16:8)
You may need an appropriate loader to handle this file type.
|       let source = {
|         type: "raster",
|         ...this.source
|       };
| 

 @ ./node_modules/vue-mapbox/src/main.js 16:0-57
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

 error  in ./node_modules/vue-mapbox/src/components/layer/VideoLayer.js

Module parse failed: Unexpected token (28:8)
You may need an appropriate loader to handle this file type.
|       const source = {
|         type: "video",
|         ...this.source
|       };
| 

 @ ./node_modules/vue-mapbox/src/main.js 14:0-55
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

 error  in ./node_modules/vue-mapbox/src/components/layer/CanvasLayer.js

Module parse failed: Unexpected token (42:8)
You may need an appropriate loader to handle this file type.
|       const source = {
|         type: "canvas",
|         ...this.source
|       };
| 

 @ ./node_modules/vue-mapbox/src/main.js 13:0-57
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

 error  in ./node_modules/vue-mapbox/src/components/layer/ImageLayer.js

Module parse failed: Unexpected token (46:8)
You may need an appropriate loader to handle this file type.
|       const source = {
|         type: "image",
|         ...this.source
|       };
| 

 @ ./node_modules/vue-mapbox/src/main.js 12:0-55
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

 error  in ./node_modules/vue-mapbox/src/components/layer/layerMixin.js

Module parse failed: Unexpected token (48:4)
You may need an appropriate loader to handle this file type.
|   mixins: [withEvents],
|   props: {
|     ...mapboxSourceProps,
|     ...mapboxLayerStyleProps,
|     ...componentProps

 @ ./node_modules/vue-mapbox/src/main.js 21:0-55
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

 error  in ./node_modules/vue-mapbox/src/components/map/mixins/withPrivateMethods.js

Module parse failed: Unexpected token (49:10)
You may need an appropriate loader to handle this file type.
|         if (this.accessToken) this.mapbox.accessToken = this.accessToken;
|         const map = new this.mapbox.Map({
|           ...this._props,
|           container: this.$refs.container,
|           style: this.mapStyle

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-mapbox/src/components/map/GlMap.vue 15:0-61
 @ ./node_modules/vue-mapbox/src/components/map/GlMap.vue
 @ ./node_modules/vue-mapbox/src/main.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

 error  in ./node_modules/vue-mapbox/src/components/layer/VectorLayer.js

Module parse failed: Unexpected token (49:8)
You may need an appropriate loader to handle this file type.
|       let source = {
|         type: "vector",
|         ...this.source
|       };
| 

 @ ./node_modules/vue-mapbox/src/main.js 15:0-57
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

 error  in ./node_modules/vue-mapbox/src/components/UI/withSelfEvents.js

Module parse failed: Unexpected token (4:58)
You may need an appropriate loader to handle this file type.
|   methods: {
|     $_emitSelfEvent(event, data = {}) {
|       this.$_emitMapEvent(event, { control: this.control, ...data });
|     },
|     /** Bind events for markers, popups and controls.

 @ ./node_modules/vue-mapbox/src/main.js 19:0-65
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/stock/StockMap.vue
 @ ./src/components/stock/StockMap.vue
 @ ./src/router/stockRouter.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server babel-polyfill ./src/main.js

Thanks for your help

**Comment by aarepuu** [comment]
Had the same issue with my project and I ended just not building vue-mapbox (you wouldn't really want to build it every time anyhow in my opinion) and using an alias that refers to the built .js file:
```

// webpack.conf.js
.......
resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
      'vue-mapbox': path.resolve(__dirname, '../node_modules/vue-mapbox/dist/vue-mapbox.umd.min.js'),
    }
  },

......

```

**Comment by tpoussard** [comment]
I tried it and it works ! Thanks a lot @aarepuu for the good tip, I'm sure it would help a lot of people ! Have a nice day :-)

**Comment by liboub** [comment]
Thanks @aarepuu  it work nice.

**Comment by jssouders** [comment]
@aarepuu I am having this same issue with vue-mapbox, but in NUXTJS.  Any idea how I would be able to apply this solution in the nuxt.config.js file?  I know there is a way to override the webpack configuration via this file, but haven't been successful trying to make it work.

**Comment by fayezgb** [comment]
@jssouders for NUXTJS I was able to fix this issue but changing the `mapbox` plugin as the following:
1. Import vue-mapbox form the dist folder:
Replace
```js
import { MglMap, MglGeolocateControl, MglNavigationControl } from "vue-mapbox";
```
With
```js
import { MglMap, MglGeolocateControl, MglNavigationControl } from "vue-mapbox/dist/vue-mapbox.umd.js";
```

2. Add the CSS styles from the following file `node_modules/vue-mapbox/dist/vue-mapbox.css` to `app.html`
