### ISSUE TITLE
setFeatureState vector layer error

### ISSUE THREAD

**Issue by antonydellavecchia** [soal/vue-mapbox#105]
Pretty sure i am getting an error because the source of a vector layer is an object,
but the orignal mapbox function requires a key for it's source, this should be fixed by just change this.source to this.sourceId? also sourceLayer instead of "source-layer"? similar error for get, I changed this to my suggestions and i got my code to work.
    
    setFeatureState(featureId, state) {
      if (this.map) {
        const params = {
          id: featureId,
          source: this.source,
          "source-layer": this.layer["source-layer"]
        };
        return this.map.setFeatureState(params, state);
      }
    }

**Comment by dmikrot** [comment]
@soal A similar issue is happening with `GeojsonLayer`, but this fix was only applied for `VectorLayer`.
