### ISSUE TITLE
How to access Leaflet methods?

### ISSUE THREAD

**Issue by LionelPaulus** [soal/vue-mapbox#124]
I would like to do this:

```javascript
var group = new L.featureGroup([marker1, marker2, marker3]);

map.fitBounds(group.getBounds());
````

But I don't know how can I access to the `L` object?

**Comment by stafyniaksacha** [comment]
You may be looking for leaflet project here: https://korigan.github.io/Vue2Leaflet/#/
This is a vuejs wrapper for mapbox: https://docs.mapbox.com/mapbox-gl-js/api/
