### ISSUE TITLE
Moving marker on zoom

### ISSUE THREAD

**Issue by img2001jpg** [soal/vue-mapbox#149]
Hi, I am experiencing a moving marker when I zoom in or out of the map... Does anyone know why this is happening?

[Demo](https://codesandbox.io/embed/vue-template-6kbvq?fontsize=14)

**Comment by img2001jpg** [comment]
just fixed this myself with importing the mapbox gl css correctly
`import 'mapbox-gl/dist/mapbox-gl.css'`

**Comment by estebanmontes** [comment]
where did u add the import?
I got the same issue the markers are moving when the I move on the map

**Comment by SALIHAdataonline** [comment]
@img2001jpg I like your demo it explains clearly the issue

**Comment by img2001jpg** [comment]
I've used it in this project: [MapContainer.vue](https://github.com/img2001jpg/digital-detox/blob/master/components/MapContainer.vue)

In my case all I had to add was `import 'mapbox-gl/dist/mapbox-gl.css'` and the marker stopped moving. It does not work on the codesandbox link though.
