### ISSUE TITLE
How to setFeatureState of a GeoJsonLayer

### ISSUE THREAD

**Issue by joshstobbs** [soal/vue-mapbox#153]
Hey there, I am trying to change the opacity of a layer on hover hover when trying to access the setFeatureState function on the component this error is thrown:

`Error: The source '[object Object]' does not exist in the map's style.`

My method looks like this and is being called on mouseenter.

```
handleMouseEnter(e) {
    const { component, layerId } = e

    component.setFeatureState(layerId, { hover: true })
}
```

If anyone could offer help that would be fantastic, I can spin up an example project as well if need be.  Thanks!

**Comment by wyznio** [comment]
I got the same error as yours. Could you please post an example code of the solution? Thanks.

**Comment by danimalweb** [comment]
Same issue here! What was the solution?

**Comment by joshstobbs** [comment]
@danimalweb @wyznio 

Sorry for the late answer on both of these - I basically just moved the listener to the layer component itself.  It wasn't the cleanest solution but it worked.

Basically just doing an `@mouseenter="handleEvent"`

If you need any help let me know - it's been a while since I've worked with this library but I'm happy to offer assistance where I can!

**Comment by adrianhalliday** [comment]
Hi @soal, I'm also struggling with this aspect of your library so far!

I have an '@mouseenter=eventHandler($event)' event listener on the <MglGeojsonLayer>, to pass the Vue $event to the handler method.

In the event handler method I'm attempting:
```
this.$refs.layerXYZ.setFeatureState(
  $event.mapboxEvent.features[0].id,
  { hover: true }
)
```

However, I get the same error above. I can see `setFeatureState` is a valid method for the layer I'm accessing via refs, but I can't find the issue with the syntax that's preventing the code from running!

@joshstobbs what was your syntax to get the setFeatureState() method to work?

**Comment by adrianhalliday** [comment]
Hi @soal I actually got this to work, by updating vue-mapbox's GeojsonLayer.js

On line 146, I replaced the function with the following:
```
setFeatureState(feature, state) {
    if (this.map) {
      return this.map.setFeatureState(feature, state);
    }
},
```

Then, in my Vue file I updated my method to the following:
```
handleMouseEnter(e) {
  const { component } = e
  let source = e.component.$options.propsData.sourceId
  let feature = e.mapboxEvent.features[0].id

  component.setFeatureState({
    source: source,
    id: feature,
  }, { hover: true })
},
```

This is using much the same syntax as the original setFeatureState() function from the Mapbox GL library.

However, I'm interested to know how it's _meant_ to be done 'properly' as per your original code, as the docs are unclear on this point. If you could clear that up I'd be very appreciative so that I can revert vue-mapbox back to it's default state and remove my modifications.
