### ISSUE TITLE
How to use the actions

### ISSUE THREAD

**Issue by SilasNiewierra** [soal/vue-mapbox#156]
Dear vue-mapbox team,

first of all, thank for this amazing library.
Regarding my issue:
If i click a button, i want my map to pan and zoom. But i want the transition between the first pitch and zoom value and the final pitch and zoom value to be smooth and animated. Therefore I would like to use panBy or zoomTo.
But I can't find a code example on how to use these functions with the correct parameters.
Can you put code examples how to call a basic action like zoomTo or panBy with actual parameters?

Thank you so much!

**Comment by Mihailo23** [comment]
`<MglMap
      ref="map"
      :accessToken="accessToken"
      :mapStyle="mapStyle"
      :center="center"
      :zoom="12"
      @load="mapLoaded"
    >`

just use in your methods:

`this.$refs.map.map.panTo({
          // any options you wish to pass
});`

**Comment by SilasNiewierra** [comment]
Thanks 👍

**Comment by jaysonmulwa** [comment]
Just what I was looking for. Thanks @Mihailo23
