### ISSUE TITLE
Getting Error: missing required property "version"

### ISSUE THREAD

**Issue by hassan-jahan** [soal/vue-mapbox#184]
Hi, Thank you for your great work

I couldn't make the base map example work. I constantly get followings :
 
Error: missing required property "version"
Error: missing required property "sources"
Error: missing required property "layers"

Here you can edit my code. I just want to show a simple map:
https://codesandbox.io/s/mystifying-dubinsky-23xwp?file=/src/App.vue

**Comment by michisp** [comment]
Hey @hassan-jahan,

here is a working example: https://codesandbox.io/s/xenodochial-satoshi-tnzg7?file=/src/App.vue. Just insert your access token.

MapStyle is just the style of the map. For center or zoom you've got other props which you can use. Take a look at the vue-mapbox and mapbox-gl docs:
https://soal.github.io/vue-mapbox/api/#props
https://docs.mapbox.com/mapbox-gl-js/api/#map

**Comment by hassan-jahan** [comment]
Oh my bad! Thank you very much!
