### ISSUE TITLE
Map not displayed

### ISSUE THREAD

**Issue by elC0mpa** [soal/vue-mapbox#192]
Hello, I am having a problem with your package, I am trying to reproduce the [base map](https://soal.github.io/vue-mapbox/guide/basemap.html#adding-map-component). First, I realized that I was assinging a bad style because the component raised an error when trying to make the http request. But now, it doesn't raise any error, and still like that, the map isn't displayed. Here is the component:
```javascript
<template>
  <q-page id="map" class="row items-center justify-evenly">
    <MglMap
      style="width: 100%"
      container="#map"
      :center="coordinates"
      :accessToken="accessToken"
      :mapStyle.sync="mapStyle"
    />
  </q-page>
</template>

<script lang="ts">
import Vue from 'vue';
import Mapbox from 'mapbox-gl';
import { MglMap } from 'vue-mapbox';
import 'mapbox-gl/dist/mapbox-gl.css';

export default Vue.extend({
  name: 'PageIndex',
  data() {
    return {
      accessToken:
        'MY_ACCESS_TOKEN',
      mapStyle: 'mapbox://styles/mapbox/streets-v11',
      coordinates: [23.119456, -82.426454]
    };
  },
  components: {
    MglMap
  },
  created() {
    this.mapbox = Mapbox;
  }
});
</script>
```

**Comment by vvavepacket** [comment]
@elC0mpa 
Did you managed to fix this?

**Comment by elC0mpa** [comment]
@vvavepacket yes I did
Do you need some help?

**Comment by vvavepacket** [comment]
@elC0mpa 
Yes I'm just getting a blank map like what you mentioned. I went to html and I can see its being occupied. Any suggestions? Thank you in advance.

![image](https://user-images.githubusercontent.com/8295642/97519866-5fd8b000-1970-11eb-91fc-69eb6c09234b.png)

**Comment by elC0mpa** [comment]
@vvavepacket I didn't believe this was the problem
But I just wrap the `MglMap` component with a `<div id=map>` and remove the id from `q-page`.
Please let me know if you solve your problem with this

**Comment by vvavepacket** [comment]
It is working thank you.
