### ISSUE TITLE
Is it possible to add a project icon to a symbol layer?

### ISSUE THREAD

**Issue by elC0mpa** [soal/vue-mapbox#194]
```javascript
myLayer: {
        id: 'layerId',
        type: 'symbol',
        source: 'barbershops-id',
        layout: {
          'icon-image': 'lar la-star'
        }
      }
```
I want to use a project icon to represent a layer, the thing is that I can use these icons outside the map and even to change the default markers slot, but if I try to add them in this map, it raises the next warning

> Image "lar la-star" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event

I would like to know what are 'sprite' properties in the style and if there is a way I can achieve this using layers and sources bacause with markers it is pretty simple

**Comment by rognstad** [comment]
Put an @load handler on the map. The event passed to that handler with include a reference to the map. You can then call map.addImage, following the Mapbox documentation.

**Comment by elC0mpa** [comment]
Thanks @rognstad, I had already solved this problem

**Comment by gorbypark** [comment]
@rognstad thank you, sir!  It always pays to search closed issues.  For anyone else who stumbles across this...

1. Add an @load to your main map component, something like this `<MglMap @load="onMapLoaded">`
2. Add a method that loads the image and adds it to the map when the map loads
```js
  methods: {
    onMapLoaded(e) {
      e.map.loadImage(
        'https://url.com/icon.png',
        (error, image) => {
          if (error) console.log(error)
          e.map.addImage('icon-for-my-layer', image)
        },
      )
    },
  }
```
3. Use the icon in a layer like so, the type needs to be `symbol` and the `icon-image:` needs to point to the name of the icons from the `e.map.addImage('icon-for-my-layer', image)` line of code from #2
```js
        layer: {
          type: 'symbol',
          'source-layer': 'my-source',
          layout: {
            'icon-image': 'icon-for-my-layer',
            'icon-size': 1,
            'icon-allow-overlap': true,
          },
        },
```
