### ISSUE TITLE
Как добавить маркеры

### ISSUE THREAD

**Issue by staticdreams** [soal/vue-mapbox#24]
Привет. Отличный компонент!
Поскольку документация пока не очень доступна по этому поводу, я попробовал сам добавить маркер. Но ничего не вышло, если просто указать координаты как в случае с mgl-popup.
Не мог бы подсказать как это сделать ?

Спасибо за твою работу

**Comment by soal** [comment]
В маркере была ошибка, она исправлена в новой версии 0.0.17.

Как добавить маркер:
Маркер принимает props `сoordinates` и `offset`.
`сoordinates` это координаты маркера
`offset` это отступ элемента маркера от этих координат в пикселях, это свойство передаётся в объект Marker MapboxGL JS (options.offset описаноое [здесь](https://www.mapbox.com/mapbox-gl-js/api#marker))
Простейший маркер:
```
    <mgl-marker :coordinates="[50, 50]" />
```
Используя слот `marker` можно передать html-элемент в качестве маркера:
```
<mgl-marker :coordinates="[50, 50]">
  <span slot="marker">I am marker!</span>
</mgl-marker>
```
Если внутрь маркера добавить попап, то он автоматически привяжется к маркеру (тоже, что вызов [setPopup](https://www.mapbox.com/mapbox-gl-js/api/#marker#setpopup)):
```
<mgl-marker :coordinates="[50, 50]">
  <span slot="marker">I am marker!</span>
  <popup>
      <h3>I am popup!</h3>
   </popup>
</mgl-marker>
```

Документация в процессе, закончу в течение нескольких дней.

**Comment by staticdreams** [comment]
Спасибо большое! А иконку у маркера можно будет персонализировать?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by soal** [comment]
> Используя слот marker можно передать html-элемент в качестве маркера:
```
<mgl-marker :coordinates="[50, 50]">
  <span slot="marker">I am marker!</span>
</mgl-marker>
```
Ну а html-элемент может быть какой угодно.

**Comment by staticdreams** [comment]
Спасибо!
