### ISSUE TITLE
Missing Mapbox GL JS CSS

### ISSUE THREAD

**Issue by jeeftor** [soal/vue-mapbox#27]
I'm trying to integrate this into an electron container.  Any idea how to resolve `Missing Mapbox GL JS CSS`

**Comment by jeeftor** [comment]
```
<style>
@import url("https://api.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.css");
@import url("https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.2.0/mapbox-gl-geocoder.css");
</style>

```

**Comment by wyattp11** [comment]
Should also mention the required CSS to get the map to show, I have the map showing finally using the following style which has to be placed in both the main.js and App.vue (if using Helloworld template):

```
<style>
@import url("https://api.tiles.mapbox.com/mapbox-gl-js/v0.45.0/mapbox-gl.css");

body { margin:0; padding:0; }

.mapboxgl-map { position: absolute; top:0; bottom:0; width: 100%; overflow: visible; }

</style>

```

**Comment by chriszrc** [comment]
If you're using the vue cli which sets up webpack css processing, you can just add this to your main .vue file:

```
import 'mapbox-gl/dist/mapbox-gl.css';
```

ref: https://github.com/mapbox/mapbox-gl-js/issues/5785#issuecomment-357374166
