### ISSUE TITLE
Is there a way to use this within a webview in Nativescript-Vue?

### ISSUE THREAD

**Issue by wyattp11** [soal/vue-mapbox#33]
I get an html error when I try to implement into Nativescript-Vue, I believe Mapbox GL is looking for an  html element to bind to, tried replacing with a stackedLayout. Do you know how to get this working within a webview element?

**Comment by soal** [comment]
I've never worked with NativeScript or NativeScript-vue. I will look into this within a few days, right now I have no idea what's going on there.
May be using native Mapbox GL library with [this](https://github.com/EddyVerbruggen/nativescript-mapbox) plugin would be better idea. Considering [this](https://github.com/EddyVerbruggen/nativescript-mapbox/issues/214) issue someone got it worked.

**Comment by wyattp11** [comment]
Yes, I've been working with that plugin too. I'm trying to move my app from Leaflet/Mapbox JS to GL or iOS SDK however the iOS/Android SDKs are lacking in features that Leaflet/GL has. So trying to use GL if possible.
