### ISSUE TITLE
Can't add GeoJSON layer to mapbox

### ISSUE THREAD

**Issue by RobertoGeuke** [soal/vue-mapbox#41]
I'm trying to add GeoJSON layer to the mapbox, so I can show a circle with a certain radius around a marker on the map. When I'm loading the webpage, I'll get an error: 

`Error: layers.radius: missing required property "source"` and `layers.radius.source: string expected, undefined found`

I think I might forget something while setting the source property on the component, but I can't seem to find what I'm forgetting or what I'm doing wrong. I'm using the following package to generate the GeoJSON object: 

My code is as followed: http://turfjs.org/docs/#circle

```
<mgl-map :accessToken="accessToken" :mapStyle.sync="mapStyle" :center="coordinates" :zoom="10">
    <mgl-marker :coordinates="coordinates"></mgl-marker>
    <mgl-geojson-layer :type="fill" :layerId="radius.properties.id" :source.sync="radius"></mgl-geojson-layer>
</mgl-map>
```
```
export default {
        components: {
            MglMap,
            MglMarker,
            MglGeojsonLayer,
        },
        data() {
            return {
                accessToken: "...",
                mapStyle:  '...',
                coordinates: [4.1451,51.8009],
                radius: circle([4.1451,51.8009], 20, {
                    properties: {
                        id: 'radius',
                        paint: {
                            'fill-color': 'blue',
                            'fill-opacity': 0.6
                        }
                    }
                }),
            }
        },
}
```

**Comment by soal** [comment]
You need to add prop 'sourceId' to layer component:
```
<mgl-geojson-layer type="fill" :sourceId="radius.properties.id" :layerId="radius.properties.id" :source.sync="radius" />
```
I will update guide in a couple of days.

**Comment by RobertoGeuke** [comment]
It works. Thanks a lot!
