### ISSUE TITLE
peerDependency to mapbox <= 2.5.13

### ISSUE THREAD

**Issue by jo-m** [soal/vue-mapbox#42]
Hi, and thanks for this project, its awesome!

I have an issue with the dependencies though. `vue-mapbox` currently prevents me from installing a newer VueJS version, as it is hardcoded to vue `<=2.5.13` in `peerDependencies` (although it's `^2.5.13` in `devDependencies`). Is this needed, or could it be changed to caret too?

Best
Jonathan

**Comment by soal** [comment]
Hi, thanks for you contribution!
Stupid mistake, fixed now in 0.0.32.

**Comment by jo-m** [comment]
cool, thanks!
