### ISSUE TITLE
Map doesn't react to most prop changes

### ISSUE THREAD

**Issue by mrobakowski** [soal/vue-mapbox#44]
Probably because of this line. I suspect this should set `initial` to false.
https://github.com/soal/vue-mapbox/blob/ef8442b4b6472fcad9b6bc291f385866c312f92b/src/components/GlMap.vue#L117

**Comment by soal** [comment]
Yeah, thanks, will be fixed in new release tomorrow.

**Comment by soal** [comment]
FIxed in 0.0.33
