### ISSUE TITLE
Popup doesn't follow new coordinates

### ISSUE THREAD

**Issue by fer22f** [soal/vue-mapbox#46]
Hello! I have a set of markers which move around, but leave their popups behind.

![image](https://user-images.githubusercontent.com/3057302/43104400-b9a411a2-8ea7-11e8-99de-3840c0f390c4.png)

I set 'em up with something like this:

```pug
  mgl-marker(v-for="marker in markers" :key="marker.id"
  :coordinates="[marker.long, marker.lat]")
    mgl-popup(:offset="12")
```

However, when they move around, popups that were open previously get stuck in their original location. I tried to fix by adding the coordinates explicitly:

```pug
  mgl-marker(v-for="marker in markers" :key="marker.id"
  :coordinates="[marker.long, marker.lat]")
    mgl-popup(:offset="12" :coordinates="[marker.long, marker.lat]")
```

But it still didn't work.

**Comment by fer22f** [comment]
Researching a bit further into this, it seems like the cause is more sinister than I initially thought, markers themselves become "free" after they have been moved and don't align correct to their correct coordinates, they slide around while the map is rotated or moved in the vertical axis... the bigger the distance of the last movement, the bigger the looseness of the marker itself.

So perhaps, the issue isn't in the popups, but in the markers themselves, while the popups are showing up in the right spot.

**Comment by soal** [comment]
Thanks for the report, I will investigate this in a couple of days.

**Comment by fer22f** [comment]
I will note that this does work correctly:

```javascript
      this.markers = []
      await this.$nextTick()
      this.markers = res.data
```
(i.e., clearing the list instead of letting Vue do magic interpolation)

The memory leak is unsustainable though:

![image](https://user-images.githubusercontent.com/3057302/43143337-f0c8bc80-8f30-11e8-81c9-2ba94412f903.png)

While moving the items instead, simply

```javascript
      this.markers = res.data
```

Yields a more sustainable memory profile:

![image](https://user-images.githubusercontent.com/3057302/43143705-c2eda25c-8f31-11e8-9055-ef4288d9c122.png)

(this is all in a development environment)

**Comment by fer22f** [comment]
Found the issue! It was self-sabotage, of course. I made marker like so:

```pug
  mgl-marker(v-for="marker in markers" :key="marker.id"
  :coordinates="[marker.lng, marker.lat]" :offset="[0, 12]")
    svg(viewBox="0 0 24 24" width=24 height=24)
```

And then I set a new size to this SVG via CSS, setting it to 32px. The internal Mapbox API probably got confused at the two values.

Anyway, I think the only thing of value that came out of this is that maybe you should look into those memory leaks I talked above.

**Comment by soal** [comment]
And it was interesting to read :) Thanks, I think memory footprint issue is worth to look into.
