### ISSUE TITLE
Unknown errors with missing property

### ISSUE THREAD

**Issue by adriandarian** [soal/vue-mapbox#48]
I am following the getting started vue-mapbox documentation and fell into some unknown console errors. The getting started link is this https://soal.github.io/vue-mapbox/#/quickstart. My vue application was created using the vue create projectName cli command and for my configs I selected vue-router, vuex, sass, babel, eslint, unit-jest, e2e-cypress. I am unsure what is causing the issue, because I imported the vue-mapbox as a ES module and I am using yarn. However my main.js file looks like this

import Vue from 'vue';
import VueMapbox from 'vue-mapbox';
import Mapbox from 'mapbox-gl';

import App from './App.vue';
import router from './router';
import store from './store';

Vue.config.productionTip = false;

Vue.use(VueMapbox, { mapboxgl: Mapbox });

new Vue({
  router,
  store,
  render: h => h(App),
}).$mount('#app');
But for some reason I cannot figure out why I am getting these 3 errors.

Error: missing required property "version"
Error: missing required property "sources"
Error: missing required property "layers"

**Comment by soal** [comment]
Must be fixed in 0.2. Feel free to reopen this issue if you still have this problem.
