### ISSUE TITLE
Add click, onMouseEnter and onMouseLeave events to markers

### ISSUE THREAD

**Issue by liteultom** [soal/vue-mapbox#68]
Hello !

Any plan on implementing the `onMouseEnter`, `onMouseLeave` and `onClick` events on marker ?

How it would work : 
```

<template>
     <mgl-map ... >
         ...
        <mgl-marker :onMouseEnter="markerMouseEnter" ... >
            ...
        </mgl-marker>
    </mgl-map>
</template>

<script>
methods : {
    markerMouseEnter(eventData) {
        console.log("Mouse entered marker "+eventData.markerId)
    }
}
<script>
```

I can't find any workaround to have a similar feature

**Comment by soal** [comment]
Yeah, check this issue with markers/popups out in a couple of days

**Comment by liteultom** [comment]
Thank you. Meanwhile I finally found a work around : listen to `mouseenter` event on the biggest html element I have in my marker icon, and re-emit `mouseenter` . Seems to work for now !

**Comment by nickforddesign** [comment]
Any update on this?

**Comment by kevinelliott** [comment]
Looking for this functionality as well!

**Comment by fergardi** [comment]
I'm interested in this as well. Any news?

**Comment by matoous** [comment]
Any news on this one?

**Comment by soal** [comment]
There is no implementation of these events in Mapbox GL JS itself, see mapbox/mapbox-gl-js#7793

There is some initial implementation: #117. 
It works, but additional testing will be appreciated.
Using internal `._element` of the marker is a workaround and don't look reliable, so please consider this feature as experimental.
