### ISSUE TITLE
Failed to mount component

### ISSUE THREAD

**Issue by jebkor** [soal/vue-mapbox#72]
Hello,

I am currently looking into using this component/library, but I am running into a major issue:

When I have installed and "used" the component, all I get the my console.log when I view the page, is this error message:
"Failed to mount component: Template or render function not defined"

Would you happen to have an idea of why this happens? When I try to downgrade, it doesn't fix it either. I am using the latest version, v.0.1.1

**Comment by soal** [comment]
Hello,

can you provide some additional info or code sample?
Specifically, what components from VueMapbox do you use? Only MglMap, Marker, etc.?

**Comment by cjaoude** [comment]
@soal i'm getting the same issue, frustrating. 
I'm using the doc example:
https://soal.github.io/vue-mapbox/guide/basemap.html#adding-map-component

Using latest Grunt, Browserify, vueify.

**Comment by soal** [comment]
@cjaoude can you please give your setup for grunt and browserify? It would be easy for me to test against it since there is a long time since I use browserify.

**Comment by jebkor** [comment]
Sorry I haven't gotten back. I was doing a simple import in my code and I was using the MglMap component as well, just like @cjaoude

**Comment by cjaoude** [comment]
@jebkor by chance you’re also using vueify, etc (above). ? Thinking this may be a single file component build issue.

**Comment by cjaoude** [comment]
@soal switched to Vue CLI, all works fine. 

But getting issue where accessToken is undefined even tho clearly has a value assigned. Ideas? Thx

Is there a Discord or Slack community for this package? Or channel

**Comment by soal** [comment]
Must be fixed in 0.2. Feel free to reopen this issue if you still have this problem.
