### ISSUE TITLE
Add paint of type is symol for GeojsonLayer

### ISSUE THREAD

**Issue by ms-7083** [soal/vue-mapbox#76]
https://github.com/soal/vue-mapbox/blob/bfffb7f4757d7e7f7f416f9750f9bb60016ef773/src/components/layer/GeojsonLayer.js#L162-L169

LINE: 162, paint is not applied because symbol is excluded.
This can not change text-color etc.

```
<template>
  <MglMap>
    <MglGeojsonLayer
      type="symbol"
      :paint="symbolPaint"
    />
  </MglMap>
</template>

<script>
export default {
  data() = {
    symbolPaint: {
      "text-color": "#FFFFFF"
    }
  }
}
</script>
```

**Comment by soal** [comment]
Must be fixed in 0.2. Feel free to reopen this issue if you still have this problem.
