### ISSUE TITLE
asyncActions is undefined

### ISSUE THREAD

**Issue by nickforddesign** [soal/vue-mapbox#84]
Given the example in the docs, I set up an event listener for the `load` event. Looking at the component, there was no property called `asyncActions`, but there was one called `actions`, which seemed to have everything there. Is this a typo in the docs?

```js
async onMapLoaded({ component }) {
  const { actions } = component;
  const bounds = new mapboxgl.LngLatBounds();
  this.features.forEach((feature) => {
    bounds.extend(feature.geometry.coordinates);
  });
  await actions.fitBounds(bounds, { padding: 100, duration: 0, maxZoom: 15 });
}

**Comment by soal** [comment]
Hmm, can you please give a link to the particular place in the docs?
As far as I can see, map actions described [here](https://soal.github.io/vue-mapbox/guide/basemap.html#map-actions) and example is:
```js
async onMapLoad(event) {
      // Here we cathing 'load' map event
      const asyncActions = event.component.actions

      const newParams = await asyncActions.flyTo({
        center: [30, 30],
        zoom: 9,
        speed: 1
      })
      console.log(newParams)
      /* => {
              center: [30, 30],
              zoom: 9,
              bearing: 9,
              pitch: 7
            }
      */
    }
```

**Comment by nickforddesign** [comment]
🤦‍♂️You're right, I misread the example.

There is a typo in the docs that isn't in your pasted example, maybe you already fixed it?

```js
aync onMapLoad(event) { // aync should be async

**Comment by soal** [comment]
Yeah, I'll fix it in next release in next couple of days.

-------- Исходное сообщение --------
Вкл 11 февр. 2019 г., 17:31, Nick Ford пишет:

**Comment by nickforddesign** [comment]
👍 Thanks! I've tried a lot of solutions for mapbox + vue and loving this library in particular!
