### ISSUE TITLE
marker added event fires twice per each marker

### ISSUE THREAD

**Issue by nickforddesign** [soal/vue-mapbox#85]
For some reason my codesandbox example doesn't render but the console shows the same issue im seeing, the `added` event is emitted twice per each marker.

https://codesandbox.io/s/qqx96pqp9

![screen shot 2019-02-12 at 10 32 48 am](https://user-images.githubusercontent.com/1086884/52646860-8fe8d280-2eb1-11e9-8b95-d708d5449a01.png)

**Comment by soal** [comment]
Fixed in `development` branch, will be released in version 0.2 soon. Just need to update documentation.

**Comment by nickforddesign** [comment]
Awesome, thank you!

**Comment by soal** [comment]
Must be fixed in 0.2. Feel free to reopen this issue if you still have this problem.
