### ISSUE TITLE
 Cannot set property 'accessToken' of undefined

### ISSUE THREAD

**Issue by cjaoude** [soal/vue-mapbox#87]
really need help with this, super annoyed. keep getting error

> Cannot set property 'accessToken' of undefined

i'm using the base map example. it doesn't see the access token. :/

```
<template>
  <div>
    <MglMap :accessToken="accessToken" :mapStyle.sync="mapStyle"/>
  </div>
</template>

<script>
import { MglMap } from 'vue-mapbox';

export default {
  components: {
    MglMap,
  },
  data() {
    return {
      accessToken: process.env.VUE_APP_MAPBOX_KEY,
      mapStyle: process.env.VUE_APP_MAPBOX_STYLE,
    };
  },
};
</script>

```

**Comment by soal** [comment]
Looks like you can get this error in Google Chrome if you not register VueMapbox as a plugin properly.
See "Register a plugin" in [docs](https://soal.github.io/vue-mapbox/guide/#using-as-es-module)

**Comment by cjaoude** [comment]
@soal tnx, you're right, typo in plugin
