### ISSUE TITLE
when @click geojson, how do i access the Feature data?

### ISSUE THREAD

**Issue by cjaoude** [soal/vue-mapbox#90]
i can't figure out how to get the geoJson Feature data from a click event. what's the object path? on mapbox it's only event.features , but here's i don't see it. tnx

https://docs.mapbox.com/mapbox-gl-js/example/polygon-popup-on-click/

**Comment by soal** [comment]
`event.mapboxEvent.features`?

**Comment by cjaoude** [comment]
Closing this, issue #66 is what I’m trying to do.

**Comment by morfair** [comment]
> `event.mapboxEvent.features`?
How to access to this? I don't see it in console.log(event).

**Comment by mdallava** [comment]
I don'k know how to access to "event.mapboxEvent.features", someone can help me ?

**Comment by wadclapp** [comment]
Having this issue too, `features` property does not exist on `event.mapboxEvent`? Has anyone figured it out?

**Comment by wadclapp** [comment]
Ok `features[0]` works, it is unrelated to vue-mapbox

**Comment by wadclapp** [comment]
For now I just manage the listeners myself

```js
methods: {
    handleClick(e) {
        console.log(e.features[0]) // works
    },
}
created() {
    this.$store.map.on('click', 'myLayerId', this.handleClick)
  },
beforeDestroy() {
    this.$store.map.off('click', 'myLayerId', this.handleClick)
},
```

When using vue emitted click event from geojson layer component I get  `Cannot read property '0' of undefined`.
