### ISSUE TITLE
As of 0.2.0, custom markers no longer work in Marker.vue

### ISSUE THREAD

**Issue by aidangarza** [soal/vue-mapbox#92]
Prior to 0.2.0, creating the mapbox marker instance happened in the `mounted` hook via the old `deferredMount` concept. Now that it has been moved to the `created` hook in 0.2.0, the `$slots.marker[0]` VNode has not yet mounted; so, `$slots.marker[0].elm` is undefined.

**Comment by soal** [comment]
Fixed in [0.2.2](https://github.com/soal/vue-mapbox/releases/tag/0.2.2)
