### ISSUE TITLE
Popups showing immediately -- want them all closed by default

### ISSUE THREAD

**Issue by kevinelliott** [soal/vue-mapbox#95]
Right now when looping through markers and setting popups, they all show up open by default. How can we make them so they are closed until the marker is clicked?

My current code:

```
    <MglMarker
      v-for="item in items"
      v-bind:key="item.id">
      <MglPopup>
        <div>
          Stuff
        </div>
      </MglPopup>
    </MglMarker>
```

**Comment by kevinelliott** [comment]
After about 2 hours of exploration of `vue-mapbox` source code and trial and error, I believe I have come up with a resolution.

```
    <MglMarker
      v-for="item in items"
      v-bind:key="item.id">
      <MglPopup @added="popupAdded">
        <div>
          Stuff
        </div>
      </MglPopup>
    </MglMarker>
```

Then a method defined in the component:

```
      popupAdded(event) {
        event.popup.remove();
      }
```

Then when the map draws initially (or when new markers arrive via prop), the popup is not showing. Clicking on the markers still allow the toggle to happen.

If this is an expected implementation, it might be good to put this in the Marker/Popup documentation since I believe this would be a default that most people will want. When you have 50+ items on the map at once, no one wants to see popups until chosen.

**Comment by aidangarza** [comment]
I agree with @kevinelliott, and used the same method he described above to close all of the popups immediately. Some of my users have hundreds of markers load on a map, and it's pretty inefficient to close them all every time the map loads.

**Comment by soal** [comment]
Hi @kevinelliott!
What you think would be the best approach to this issue? I'm thinking of adding `showed` prop, `false` by default, or, maybe, try to utilize `v-show` directive, although it's looks non-trivial to implement.

**Comment by fergardi** [comment]
I'm also interested in this as well. Any progress?

**Comment by soal** [comment]
#114

**Comment by soal** [comment]
`showed` prop added in version [0.3](https://github.com/soal/vue-mapbox/releases/tag/0.3.0).
