### ISSUE TITLE
Change marker color after already added to map?

### ISSUE THREAD

**Issue by kevinelliott** [soal/vue-mapbox#96]
I have markers on the map already, and when some event occurs (user clicks on it or clicks on something related elsewhere on the page), I would like to dynamically change the color of the marker. How can we accomplish this?

**Comment by aidangarza** [comment]
@kevinelliott, I solved this problem by including the color in the `key` prop, if you are rendering a list of markers.

**Comment by aidangarza** [comment]
Similarly, `type` is not dynamically updated on geojson layers, but you can include the type in the `layerId` prop and it will update when changed.

**Comment by kevinelliott** [comment]
@aidangarza Can you elaborate about including the color in the key? Does this just force the component instance to change or do you need to extract the color out of the key in some manner to reflect?

**Comment by kevinelliott** [comment]
@aidangarza I resolved it, thank you!

**Comment by Stuart98** [comment]
@kevinelliott Are you able to share how you solved the problem? Thanks!

**Comment by DevDast** [comment]
> @kevinelliott, I solved this problem by including the color in the `key` prop, if you are rendering a list of markers.
> 
> ```
> <template>
>   <mgl-map ...>
>     <mgl-marker v-for="(marker, i) in markers"
>       :color="marker.color"
>       :key="i + '_' + marker.color"
>       ... />
>   </mgl-map>
> </template>
> ```

Thx to you, it helps me so much !
So, it is a real bug or not ?
